### ISSUE TITLE
Jade support

### ISSUE THREAD

**Issue by ddavison** [Glavin001/atom-preview#8]

**Comment by chharvey** [comment]
I'm still getting the following error:

> Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

Please help.

**Comment by Glavin001** [comment]
@chharvey forward to #90. 
I'll be working on it after my exams. I tried to fix it, however since I cannot reproduce it's difficult.

**Comment by azulacamilo** [comment]
Hey guys I'm getting the following error when I try to preview jade files:

![screen shot 2016-03-16 at 09 39 48](https://cloud.githubusercontent.com/assets/9724087/13806297/1098c932-eb5b-11e5-9c9d-9e941016102e.png)

**Comment by Glavin001** [comment]
@azulacamilo please create a new issue and tell us as much information as you can to help us reproduce. Thanks.
