### ISSUE TITLE
LiveScript support

### ISSUE THREAD

**Issue by legomind** [Glavin001/atom-preview#89]
See https://github.com/gkz/LiveScript

**Comment by Necromos** [comment]
+1 would be nice to have it here

**Comment by Glavin001** [comment]
I'd be happy to review and merge a Pull Request implementing this feature.
The applicable file is: https://github.com/Glavin001/atom-preview/blob/master/lib/renderer.coffee#L44
Thanks!

**Comment by Necromos** [comment]
@Glavin001 Actually I found that there **is** `LiveScript` in code but it is not mentioned in Readme.md. I will make some changes to readme and bump version to `livescript` npm package which is newer.
