### ISSUE TITLE
CJSX (React) support 

### ISSUE THREAD

**Issue by ScreenDriver** [Glavin001/atom-preview#96]
Would it be possible to add CJSX support? CJSX provides React JSX support for CoffeeScript. See [here](https://github.com/jsdf/coffee-react-transform) and [here](https://github.com/jsdf/coffee-react)

**Comment by Glavin001** [comment]
Definitely possible. 

Please let me know:
- [ ] which one (1) of those projects you would like to be used -- whichever you find more complete and handles the best.
- [ ] a sample input file and respective output file for testing
- [ ] is there any language packages for Atom that you use? what are they?

Of course, it is easy to add support for a new previewer so feel free to submit a Pull Request. The applicable code can be found at https://github.com/Glavin001/atom-preview/blob/master/lib/renderer.coffee#L44

**Comment by ScreenDriver** [comment]
Thank you for the link to the CoffeeScript renderer. I will try ta make a pull request in the next couple of days.

**Comment by ScreenDriver** [comment]
Pull request #97 already done :wink:

**Comment by Glavin001** [comment]
Thanks for the reminder. It was on my personal TODO list to review it. :smiley:

**Comment by ScreenDriver** [comment]
No stress :smile:

**Comment by Glavin001** [comment]
Published to v.0.16.0
