### ISSUE TITLE
Pass filename to Jade renderer

### ISSUE THREAD

**Issue by lasaro-dumer** [Glavin001/atom-preview#98]
I have a similar problem of the #23 , but mine is with Jade, and not stylus

Stylus works fine for me, but jade doesn't =/

I tried the '@require' some times on jade, but had no luck
It's different on jade?

![image](https://cloud.githubusercontent.com/assets/7923619/8014783/e028de36-0ba9-11e5-911d-605352247bf6.png)

**Comment by Glavin001** [comment]
Here is the applicable code: https://github.com/Glavin001/atom-preview/blob/master/lib/renderer.coffee#L94-L101

From the docs, you're going to want to set `filename` field in the `options`: 
- docs: https://www.npmjs.com/package/jade#api
- `options`: https://github.com/Glavin001/atom-preview/blob/master/lib/renderer.coffee#L96

I would accept a Pull Request that resolved this issue.
